from sqlalchemy import Column, Integer, String

from database.base import Base


class LineName(Base):
    __tablename__ = 'lines_names'

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    name = Column(String)

    def __init__(self, db):
        self.db = db

    def get_all(self):
        return self.db.query(LineName).all()

    def seed(self):
        names = [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9 AMARILLO",
            "9 VERDE",
            "10",
            "11",
            "12",
            "13",
            "14 AZUL",
            "14 ROJO",
            "15",
            "16 AZUL",
            "16 ROJO",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22 AMARILLO",
            "22 ROJO",
            "23",
            "24",
            "25",
            "26",
            "27 AZUL",
            "27 ROJO",
            "28 AMARILLO",
            "28 VERDE",
            "29",
            "30",
            "31",
            "32 ROJO",
            "32 VERDE",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "43 LAGUNA",
            "44 AZUL",
            "44 ROJO",
            "45",
            "46",
            "47",
            "48",
            "49",
            "50",
            "51",
            "52",
            "53",
            "54",
            "55",
            "56",
            "57",
            "58",
            "59",
            "60 ROJO",
            "60 VERDE",
            "61",
            "62 NARANJA",
            "62 VERDE",
            "63",
            "64 AMARILLO",
            "64 ROJO",
            "65",
            "66 AZUL",
            "66 ROJO",
            "67",
            "68",
            "69",
            "70",
            "71",
            "72",
            "73",
            "74",
            "75",
            "76",
            "77",
            "78",
            "79",
            "80",
            "81",
            "82",
            "83",
            "84",
            "85",
            "85 FORTALEZA",
            "86",
            "87",
            "88 AMARILLO",
            "88 AZUL",
            "89",
            "90",
            "92",
            "94",
            "96 AMARILLO",
            "96 ROJO",
            "97",
            "98",
            "99",
            "100",
            "101 ANGOSTURA",
            "103",
            "104 C",
            "104 ROJO",
            "105 ROJO",
            "105 VERDE",
            "106",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
            "113",
            "115",
            "116",
            "119 AZUL",
            "119 ROJO",
            "120",
            "121",
            "122",
            "123",
            "124",
            "125",
            "126",
            "127",
            "129",
            "130",
            "131 COTOCA",
            "132",
            "132 MONTERO",
            "133 EL TORNO",
            "133 LA GUARDIA",
            "135 VIRU VIRU",
            "136 INTERMUNICIPAL",
            "136 URBANO",
            "137 LAS BRECHAS",
            "140 AZUL",
            "140 ROJO",
            "141",
            "151"
        ]

        for name in names:
            line_name = LineName(self.db)
            line_name.name = name
            self.db.add(line_name)
            self.db.commit()
        return self.db.query(LineName).all()
